- name: Install Semaphore via Snap
  hosts: all
  become: yes

  tasks:
    - name: Update apt and install Snapd
      apt:
        name: snapd
        state: present
        update_cache: yes

    - name: Ensure snapd is started and enabled
      systemd:
        name: snapd
        state: started
        enabled: yes

    - name: Install Semaphore using Snap
      snap:
        name: semaphore
        state: present
